# Generated by Django 5.2.4 on 2025-07-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-status"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.BooleanField(default=False, help_text="Виконано?"),
        ),
    ]
