# Generated by Django 5.2.4 on 2025-07-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_options_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="tasks",
            field=models.ManyToManyField(to="todo.task"),
        ),
    ]
