# Generated by Django 5.2.4 on 2025-07-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_tag_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="tasks",
        ),
    ]
